[package]
name = "reference_and_borrow"
version = "0.1.0"
authors = ["matsui <matsui@posl.ait.kyushu-u.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
